let expansion={bounty:0,bountyGoal:3,bountyReward:100,bestiary:[],wins:0};
function expansionSave(){localStorage.setItem('ccExpansion',JSON.stringify(expansion))}
try{const x=localStorage.getItem('ccExpansion');if(x)expansion=Object.assign(expansion,JSON.parse(x))}catch(e){}
const baseWin=win;
win=function(){baseWin();expansion.wins++;if(enemy&&!expansion.bestiary.includes(enemy.name))expansion.bestiary.push(enemy.name);if(expansion.bounty>0){expansion.bounty++;if(expansion.bounty>=expansion.bountyGoal){hero.gold+=expansion.bountyReward;log(`🎯 BOUNTY COMPLETE! +${expansion.bountyReward} gold!`);expansion.bounty=0;expansion.bountyGoal=3+roll(5);expansion.bountyReward+=25}}expansionSave()};
town=function(){scene('🏘️ Emberfall — EXPANDED','The adventurer capital keeps growing. New systems await!',`<button onclick="crypt()">☠️ Crypt</button><button onclick="wilds()">🌲 Wilds</button><button onclick="guild()">📜 Guild</button><button onclick="shop()">⚒️ Market</button><button onclick="inn()">🛏️ Inn</button><button onclick="arena()">🏟️ Arena</button><button onclick="companions()">🐾 Companions</button><button onclick="crafting()">🔨 Crafting</button><button onclick="training()">🎯 Training</button><button onclick="bountyBoard()">🎯 Bounty Board</button><button onclick="bestiary()">📖 Bestiary</button><button onclick="endlessMode()">♾️ Endless Mode</button><button onclick="worldBoss()">🌋 World Boss</button><button onclick="fortune()">🔮 Fortune</button><button onclick="character()">📊 Character</button>`)};
function bountyBoard(){scene('🎯 Bounty Board',`Defeat <b>${expansion.bountyGoal}</b> monsters. Progress: <b>${expansion.bounty}/${expansion.bountyGoal}</b>. Reward: <b>${expansion.bountyReward} gold</b>.`,`<button onclick="startBounty()">Accept / Refresh Bounty</button><button onclick="town()">Back</button>`)}
function startBounty(){if(expansion.bounty===0){expansion.bountyGoal=3+roll(5);expansion.bountyReward=100+roll(100);log('🎯 New bounty accepted!')}else log(`🎯 Progress: ${expansion.bounty}/${expansion.bountyGoal}`);expansionSave();bountyBoard()}
function bestiary(){scene('📖 Bestiary',`Creatures discovered: <b>${expansion.bestiary.length}/${enemies.length}</b><p>${expansion.bestiary.join(' • ')||'None yet.'}</p><p>🏆 Victories: ${expansion.wins}</p>`,`<button onclick="town()">Back</button>`)}
function endlessMode(){const i=roll(enemies.length)-1;log('♾️ ENDLESS MODE: empowered enemy!');const old=hero.level;hero.level+=Math.max(2,Math.floor(hero.level/2));encounter(i);hero.level=old}
function worldBoss(){scene('🌋 WORLD BOSS','The World Eater has awakened.',`<button onclick="worldBossFight()">⚡ SUMMON THE WORLD EATER</button><button onclick="town()">Back</button>`)}
function worldBossFight(){enemy={name:'The World Eater',icon:'🌋',boss:true,maxHp:180+hero.level*25,hp:180+hero.level*25,atk:18+hero.level,def:10+Math.floor(hero.level/2),xp:250+hero.level*15,gold:250+hero.level*20};combat('🌋 The sky cracks open!')}
function fortune(){const r=roll(6);if(r===1){hero.gold+=100;log('🔮 GOLDEN PROPHECY! +100 gold.')}else if(r===2){hero.atk+=2;log('🔮 Warrior Vision! +2 ATK.')}else if(r===3){hero.def+=2;log('🔮 Guardian Vision! +2 DEF.')}else if(r===4){hero.maxHp+=10;hero.hp+=10;log('🔮 Vitality Vision! +10 Max HP.')}else if(r===5){hero.inventory.push('💎 Ancient Gem');log('🔮 Treasure Vision! +1 Gem.')}else{hero.inventory.push('📜 Ancient Scroll');log('🔮 Dark Vision! You found a Scroll.')}update();expansionSave();town()}
