const classes={warrior:{name:'Warrior',icon:'⚔️',hp:34,atk:7,def:5,desc:'Tough melee fighter. Gains extra damage on critical hits.'},mage:{name:'Mage',icon:'🔮',hp:22,atk:10,def:2,desc:'Fragile spellcaster with powerful attacks.'},rogue:{name:'Rogue',icon:'🗡️',hp:26,atk:8,def:3,desc:'Fast striker with a chance to strike twice.'},ranger:{name:'Ranger',icon:'🏹',hp:28,atk:8,def:4,desc:'Versatile hunter with reliable ranged attacks.'}};
const enemies=[['Goblin Scout','👺',18,5,2,12],['Crypt Spider','🕷️',24,6,3,18],['Bone Knight','💀',32,8,5,30],['Grave Wyrm','🐉',48,10,6,55]];
let hero=null, enemy=null, selected=null;
const $=id=>document.getElementById(id); const roll=n=>Math.floor(Math.random()*n)+1;
function log(t){$('log').insertAdjacentHTML('beforeend',`<div class="logline">${t}</div>`);$('log').scrollTop=$('log').scrollHeight}
Object.entries(classes).forEach(([id,c])=>{$('classes').insertAdjacentHTML('beforeend',`<div class="classCard" data-class="${id}"><div class="classIcon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p><small>HP ${c.hp} • ATK ${c.atk} • DEF ${c.def}</small></div>`)})
document.querySelectorAll('.classCard').forEach(x=>x.onclick=()=>{document.querySelectorAll('.classCard').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');selected=x.dataset.class;$('startBtn').disabled=false});
$('startBtn').onclick=()=>{const c=classes[selected];hero={name:'Adventurer',class:selected,maxHp:c.hp,hp:c.hp,atk:c.atk,def:c.def,level:1,xp:0,gold:50,inventory:['🧪 Healing Potion'],kills:0};$('character-setup').classList.add('hidden');$('game').classList.remove('hidden');update();town();log('Your adventure begins in Emberfall.')};
function update(){hero.hp=Math.max(0,hero.hp);$('heroName').textContent=hero.name;$('heroClass').textContent=classes[hero.class].name;$('hp').textContent=`${hero.hp}/${hero.maxHp}`;$('level').textContent=hero.level;$('xp').textContent=`${hero.xp}/${hero.level*30}`;$('gold').textContent='🪙 '+hero.gold}
function scene(title,text,buttons=''){ $('scene').innerHTML=`<h2 class="sceneTitle">${title}</h2><div class="sceneText">${text}</div><div class="choices">${buttons}</div>`}
function town(){scene('Emberfall','A lantern-lit frontier town sits at the edge of the Whispering Wilds. The old crypt waits beyond the graveyard.',`<button onclick="crypt()">☠️ Enter the Old Crypt</button><button onclick="wilds()">🌲 Explore the Wilds</button><button onclick="heal()">🧪 Rest at the Inn — 10 gold</button><button onclick="character()">📜 View Character</button>`)}
function crypt(){scene('The Old Crypt','Cold air crawls from the stairway. Somewhere below, something scratches stone.',`<button onclick="encounter(0)">Descend</button><button onclick="encounter(1)">Take the sealed passage</button><button onclick="town()">Retreat to town</button>`)}
function wilds(){scene('Whispering Wilds','Trees bend over a moonlit trail. You hear movement in the brush.',`<button onclick="encounter(${roll(2)})">Investigate the sound</button><button onclick="findHerb()">Gather herbs</button><button onclick="town()">Return to town</button>`)}
function encounter(i){enemy={name:enemies[i][0],icon:enemies[i][1],maxHp:enemies[i][2]+hero.level*3,hp:enemies[i][2]+hero.level*3,atk:enemies[i][3]+hero.level,def:enemies[i][4],xp:enemies[i][5],gold:roll(10)+enemies[i][5]};combat()}
function combat(msg=''){scene(enemy.name,`<div class="enemy">${enemy.icon}</div><b>HP ${enemy.hp}/${enemy.maxHp}</b><div class="bar"><div class="fill" style="width:${enemy.hp/enemy.maxHp*100}%"></div></div><p>${msg}</p><div class="dice">🎲 ${roll(20)}</div>`,`<button onclick="attack()">⚔️ Attack</button><button onclick="power()">✨ Class Ability</button><button onclick="potion()">🧪 Drink Potion</button><button onclick="run()">🏃 Flee</button>`)}
function attack(){let d=roll(20),damage=Math.max(1,roll(6)+hero.atk-enemy.def);if(d===20){damage*=2;log('Critical hit!')}else if(d===1){damage=0;log('Natural 1 — you miss!')}else log(`You rolled ${d} and dealt ${damage} damage.`);enemy.hp-=damage;if(enemy.hp<=0)return win();enemyTurn()}
function power(){let d=roll(20),damage=hero.class==='mage'?roll(12)+hero.atk:roll(8)+hero.atk;if(d>=15){enemy.hp-=damage;log(`${classes[hero.class].name} ability succeeds for ${damage} damage!`)}else log(`Ability roll ${d}: it fails!`);if(enemy.hp<=0)return win();enemyTurn()}
function enemyTurn(){let damage=Math.max(0,roll(6)+enemy.atk-hero.def);hero.hp-=damage;log(`${enemy.name} hits you for ${damage}.`);if(hero.hp<=0){hero.hp=hero.maxHp;hero.gold=Math.max(0,hero.gold-10);update();scene('Defeated','You awaken at the inn, bruised but alive. You lost 10 gold.',`<button onclick="town()">Return to town</button>`);return}update();combat()}
function win(){hero.xp+=enemy.xp;hero.gold+=enemy.gold;hero.kills++;log(`Victory! +${enemy.xp} XP and +${enemy.gold} gold.`);if(hero.xp>=hero.level*30){hero.xp-=hero.level*30;hero.level++;hero.maxHp+=5;hero.hp=hero.maxHp;hero.atk++;hero.def++;log(`LEVEL UP! You are now level ${hero.level}.`)}update();scene('Victory!',`The ${enemy.name} falls. <span class="loot">+${enemy.xp} XP</span><span class="loot">+${enemy.gold} gold</span>`,`<button onclick="crypt()">Continue through the crypt</button><button onclick="town()">Return to town</button>`)}
function run(){if(roll(20)>=10){log('You escape!');town()}else{log('You fail to escape.');enemyTurn()}}
function potion(){let i=hero.inventory.indexOf('🧪 Healing Potion');if(i<0)return log('No potions left!');hero.inventory.splice(i,1);hero.hp=Math.min(hero.maxHp,hero.hp+12);log('You recover 12 HP.');update();enemyTurn()}
function heal(){if(hero.gold<10)return log('Not enough gold.');hero.gold-=10;hero.hp=hero.maxHp;update();log('You rest at the Emberfall Inn.');town()}
function findHerb(){hero.inventory.push('🌿 Wild Herb');hero.gold+=roll(5);update();log('You gather a useful herb and find some loose coins.');wilds()}
function character(){scene('Character Sheet',`<div class="statgrid"><div class="stat">⚔️ Class<br><b>${classes[hero.class].name}</b></div><div class="stat">⭐ Level<br><b>${hero.level}</b></div><div class="stat">❤️ HP<br><b>${hero.hp}/${hero.maxHp}</b></div><div class="stat">⚔️ Attack<br><b>${hero.atk}</b></div><div class="stat">🛡️ Defense<br><b>${hero.def}</b></div><div class="stat">☠️ Victories<br><b>${hero.kills}</b></div></div><p>Inventory: ${hero.inventory.join(' • ')||'Empty'}</p>`,`<button onclick="town()">Back to town</button>`)}
function inventory(){character()}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>window[b.dataset.action]?.());