const classes={warrior:{name:'Warrior',icon:'⚔️',hp:38,atk:7,def:6,ability:'Power Strike'},mage:{name:'Mage',icon:'🔮',hp:24,atk:10,def:2,ability:'Arcane Blast'},rogue:{name:'Rogue',icon:'🗡️',hp:28,atk:8,def:4,ability:'Shadow Strike'},ranger:{name:'Ranger',icon:'🏹',hp:30,atk:8,def:5,ability:'Aimed Shot'},cleric:{name:'Cleric',icon:'✝️',hp:32,atk:6,def:6,ability:'Holy Smite'},paladin:{name:'Paladin',icon:'🛡️',hp:36,atk:7,def:7,ability:'Divine Strike'},warlock:{name:'Warlock',icon:'🌀',hp:26,atk:11,def:3,ability:'Soul Bolt'},druid:{name:'Druid',icon:'🌿',hp:30,atk:7,def:5,ability:'Thorn Burst'}};
const enemies=[['Goblin Scout','👺',18,5,2,12,8],['Crypt Spider','🕷️',24,6,3,18,12],['Bandit','🥷',27,7,3,20,14],['Orc Brute','👹',36,8,5,28,18],['Bone Knight','💀',42,9,6,34,24],['Vampire','🧛',50,10,6,45,32],['Grave Wyrm','🐉',65,12,7,70,55],['Ancient Dragon','🐲',110,15,9,150,120]];
const items={potion:{name:'🧪 Healing Potion',heal:18},greater:{name:'💚 Greater Potion',heal:35},bomb:{name:'💣 Fire Bomb',damage:20}};
const quests=[{id:'goblins',title:'Goblin Trouble',desc:'Defeat 3 Goblins.',goal:3,reward:60},{id:'spiders',title:'Web of Fear',desc:'Defeat 3 Crypt Spiders.',goal:3,reward:80},{id:'wyrm',title:'Slay the Grave Wyrm',desc:'Defeat the Grave Wyrm.',goal:1,reward:150}];
let hero=null,enemy=null,selected=null,questState={goblins:0,spiders:0,wyrm:0},activeQuest=null;
const $=id=>document.getElementById(id); const roll=n=>Math.floor(Math.random()*n)+1;
function log(t){$('log').insertAdjacentHTML('beforeend',`<div class="logline">${t}</div>`);$('log').scrollTop=$('log').scrollHeight}
Object.entries(classes).forEach(([id,c])=>{$('classes').insertAdjacentHTML('beforeend',`<div class="classCard" data-class="${id}"><div class="classIcon">${c.icon}</div><h3>${c.name}</h3><p>${c.ability}: ${c.name==='Mage'?'devastating magic':c.desc||'A unique adventurer.'}</p><small>HP ${c.hp} • ATK ${c.atk} • DEF ${c.def}</small></div>`)})
document.querySelectorAll('.classCard').forEach(x=>x.onclick=()=>{document.querySelectorAll('.classCard').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');selected=x.dataset.class;$('startBtn').disabled=false});
$('startBtn').onclick=()=>{const c=classes[selected];hero={name:'Adventurer',class:selected,maxHp:c.hp,hp:c.hp,atk:c.atk,def:c.def,level:1,xp:0,gold:50,inventory:[items.potion.name,items.potion.name],kills:0,weapon:'Rusty Weapon',armor:'Traveler Armor',potions:2};$('character-setup').classList.add('hidden');$('game').classList.remove('hidden');update();town();log('Your adventure begins in Emberfall.');saveGame()};
function update(){hero.hp=Math.max(0,hero.hp);$('heroName').textContent=hero.name;$('heroClass').textContent=classes[hero.class].name;$('hp').textContent=`${hero.hp}/${hero.maxHp}`;$('level').textContent=hero.level;$('xp').textContent=`${hero.xp}/${hero.level*40}`;$('gold').textContent='🪙 '+hero.gold}
function scene(title,text,buttons=''){ $('scene').innerHTML=`<h2 class="sceneTitle">${title}</h2><div class="sceneText">${text}</div><div class="choices">${buttons}</div>`}
function town(){scene('🏘️ Emberfall','The frontier town has grown into a bustling adventurer hub. Visit the guild, blacksmith, market, or head into danger.',`<button onclick="crypt()">☠️ Explore the Crypt</button><button onclick="wilds()">🌲 Explore the Wilds</button><button onclick="guild()">📜 Adventurer Guild</button><button onclick="shop()">⚒️ Blacksmith & Market</button><button onclick="inn()">🛏️ Inn</button><button onclick="character()">📊 Character</button>`)}
function crypt(){scene('☠️ The Old Crypt','Ancient halls twist beneath the graveyard. Deeper floors contain stronger enemies and legendary treasure.',`<button onclick="encounter(0)">Floor 1 — Goblin Scout</button><button onclick="encounter(1)">Floor 2 — Crypt Spider</button><button onclick="encounter(4)">Floor 3 — Bone Knight</button><button onclick="encounter(5)">Floor 4 — Vampire</button><button onclick="encounter(6)">💀 Boss — Grave Wyrm</button><button onclick="town()">Return</button>`)}
function wilds(){scene('🌲 Whispering Wilds','A huge forest surrounds Emberfall. Ruins, monsters, herbs, and hidden paths await.',`<button onclick="encounter(2)">Investigate the bandits</button><button onclick="encounter(3)">Follow the roar</button><button onclick="findHerb()">🌿 Gather herbs</button><button onclick="ancientRuins()">🏛️ Search ancient ruins</button><button onclick="town()">Return</button>`)}
function ancientRuins(){let r=roll(20);if(r>=16){hero.gold+=40;hero.inventory.push('💎 Ancient Gem');log('You discover an Ancient Gem and 40 gold!');update()}else log('The ruins are empty, but you find a hidden inscription.');scene('🏛️ Ancient Ruins',r>=16?'A secret chamber opens!':'Dusty stone corridors reveal forgotten history.',`<button onclick="wilds()">Back to wilds</button>`)}
function encounter(i){const e=enemies[i];enemy={name:e[0],icon:e[1],maxHp:e[2]+Math.max(0,hero.level-1)*5,hp:e[2]+Math.max(0,hero.level-1)*5,atk:e[3]+Math.max(0,hero.level-1),def:e[4],xp:e[5],gold:roll(e[6])+e[6]};combat()}
function combat(msg=''){scene(enemy.name,`<div class="enemy">${enemy.icon}</div><b>HP ${enemy.hp}/${enemy.maxHp}</b><div class="bar"><div class="fill" style="width:${Math.max(0,enemy.hp/enemy.maxHp*100)}%"></div></div><p>${msg}</p><div class="dice">🎲 Roll for action</div>`,`<button onclick="attack()">⚔️ Attack</button><button onclick="power()">✨ ${classes[hero.class].ability}</button><button onclick="potion()">🧪 Use Potion</button><button onclick="bomb()">💣 Fire Bomb</button><button onclick="defend()">🛡️ Defend</button><button onclick="run()">🏃 Flee</button>`)}
function attack(){let d=roll(20),damage=Math.max(1,roll(8)+hero.atk-enemy.def);if(d===20){damage*=2;log('💥 CRITICAL HIT!')}else if(d===1){damage=0;log('Natural 1 — you miss!')}else log(`You rolled ${d} and dealt ${damage} damage.`);enemy.hp-=damage;if(enemy.hp<=0)return win();enemyTurn()}
function power(){let d=roll(20),damage=hero.class==='mage'||hero.class==='warlock'?roll(14)+hero.atk:roll(10)+hero.atk;if(hero.class==='rogue'&&d>=12)damage*=2;if(hero.class==='cleric'&&d>=15)hero.hp=Math.min(hero.maxHp,hero.hp+8);if(d>=13){enemy.hp-=damage;log(`${classes[hero.class].ability} succeeds for ${damage} damage!`)}else log(`Ability roll ${d}: it fails!`);if(enemy.hp<=0)return win();enemyTurn()}
function enemyTurn(){let damage=Math.max(0,roll(8)+enemy.atk-hero.def);hero.hp-=damage;log(`${enemy.name} hits you for ${damage}.`);if(hero.hp<=0){hero.hp=hero.maxHp;hero.gold=Math.max(0,hero.gold-15);update();saveGame();scene('💀 Defeated','You awaken at the inn. The monsters took some of your gold.',`<button onclick="town()">Return to town</button>`);return}update();combat()}
function win(){hero.xp+=enemy.xp;hero.gold+=enemy.gold;hero.kills++;if(enemy.name.includes('Goblin'))questState.goblins++;if(enemy.name.includes('Spider'))questState.spiders++;if(enemy.name.includes('Grave Wyrm'))questState.wyrm++;log(`🏆 Victory! +${enemy.xp} XP and +${enemy.gold} gold.`);if(hero.xp>=hero.level*40){hero.xp-=hero.level*40;hero.level++;hero.maxHp+=7;hero.hp=hero.maxHp;hero.atk++;hero.def++;log(`⭐ LEVEL UP! You are now level ${hero.level}.`)}update();saveGame();scene('🏆 Victory!',`The ${enemy.name} falls. <span class="loot">+${enemy.xp} XP</span><span class="loot">+${enemy.gold} gold</span>`,`<button onclick="crypt()">Continue exploring</button><button onclick="lootChest()">🎁 Search for treasure</button><button onclick="town()">Return to town</button>`)}
function lootChest(){let r=roll(20);if(r>=18){hero.inventory.push('👑 Legendary Relic');hero.atk+=3;log('🌟 LEGENDARY LOOT! You found a Relic of Power (+3 ATK).')}else if(r>=12){hero.inventory.push(items.greater.name);log('💚 You found a Greater Potion.')}else{hero.gold+=roll(30);log('🪙 You found hidden gold.')}update();saveGame();town()}
function run(){if(roll(20)>=10){log('You escape!');town()}else{log('You fail to escape.');enemyTurn()}}
function potion(){let i=hero.inventory.indexOf(items.potion.name);if(i<0)return log('No potions left!');hero.inventory.splice(i,1);hero.hp=Math.min(hero.maxHp,hero.hp+items.potion.heal);log(`You recover ${items.potion.heal} HP.`);update();enemyTurn()}
function bomb(){let i=hero.inventory.indexOf(items.bomb.name);if(i<0){hero.inventory.push(items.bomb.name);log('You had no bomb, but discover one in your pack!');return}hero.inventory.splice(i,1);enemy.hp-=items.bomb.damage;log(`💣 Fire Bomb deals ${items.bomb.damage} damage!`);if(enemy.hp<=0)return win();enemyTurn()}
function defend(){let old=hero.def;hero.def+=5;log('You raise your guard.');enemyTurn();hero.def=old}
function heal(){if(hero.gold<10)return log('Not enough gold.');hero.gold-=10;hero.hp=hero.maxHp;update();log('You rest at the Emberfall Inn.');town()}
function inn(){scene('🛏️ Emberfall Inn','A warm fire, fresh food, and a place to recover.',`<button onclick="heal()">Rest and fully heal — 10 gold</button><button onclick="town()">Back</button>`)}
function findHerb(){hero.inventory.push('🌿 Wild Herb');hero.gold+=roll(5);update();log('You gather a useful herb and find some loose coins.');wilds()}
function guild(){scene('📜 Adventurer Guild','The guild posts dangerous jobs. Complete them for bonus rewards.',quests.map(q=>`<button onclick="takeQuest('${q.id}')">${q.title} — ${q.desc} Reward: ${q.reward}g</button>`).join('')+`<button onclick="town()">Back</button>`)}
function takeQuest(id){activeQuest=id;log(`Quest accepted: ${quests.find(q=>q.id===id).title}`);guild()}
function claimQuest(){if(!activeQuest)return log('No active quest.');let q=quests.find(x=>x.id===activeQuest),progress=questState[q.id];if(progress<q.goal)return log(`Quest progress: ${progress}/${q.goal}`);hero.gold+=q.reward;hero.xp+=q.reward;log(`🎉 Quest complete! +${q.reward} gold and XP.`);activeQuest=null;update();saveGame();guild()}
function shop(){scene('⚒️ Blacksmith & Market','Upgrade your gear and stock up for the journey.',`<button onclick="buyPotion()">🧪 Potion — 15g</button><button onclick="buyBomb()">💣 Fire Bomb — 25g</button><button onclick="upgradeWeapon()">⚔️ Upgrade Weapon — 50g</button><button onclick="upgradeArmor()">🛡️ Upgrade Armor — 50g</button><button onclick="town()">Back</button>`)}
function buyPotion(){if(hero.gold<15)return log('Not enough gold.');hero.gold-=15;hero.inventory.push(items.potion.name);update();shop()}
function buyBomb(){if(hero.gold<25)return log('Not enough gold.');hero.gold-=25;hero.inventory.push(items.bomb.name);update();shop()}
function upgradeWeapon(){if(hero.gold<50)return log('Not enough gold.');hero.gold-=50;hero.atk+=2;hero.weapon='Forged Weapon';log('⚔️ Your weapon is upgraded!');update();shop()}
function upgradeArmor(){if(hero.gold<50)return log('Not enough gold.');hero.gold-=50;hero.def+=2;hero.armor='Forged Armor';log('🛡️ Your armor is upgraded!');update();shop()}
function character(){scene('📊 Character Sheet',`<div class="statgrid"><div class="stat">⚔️ Class<br><b>${classes[hero.class].name}</b></div><div class="stat">⭐ Level<br><b>${hero.level}</b></div><div class="stat">❤️ HP<br><b>${hero.hp}/${hero.maxHp}</b></div><div class="stat">⚔️ Attack<br><b>${hero.atk}</b></div><div class="stat">🛡️ Defense<br><b>${hero.def}</b></div><div class="stat">☠️ Victories<br><b>${hero.kills}</b></div><div class="stat">🗡️ Weapon<br><b>${hero.weapon}</b></div><div class="stat">🛡️ Armor<br><b>${hero.armor}</b></div></div><p><b>Inventory:</b> ${hero.inventory.join(' • ')||'Empty'}</p><p><b>Active Quest:</b> ${activeQuest?quests.find(q=>q.id===activeQuest).title:'None'}</p><button onclick="claimQuest()">📜 Check Quest Progress</button><button onclick="saveGame()">💾 Save Game</button><button onclick="loadGame()">📂 Load Game</button><button onclick="town()">Back</button>`)}
function inventory(){character()}
function saveGame(){if(!hero)return;localStorage.setItem('cryptsCreaturesSave',JSON.stringify({hero,questState,activeQuest}));log('💾 Game saved.')}
function loadGame(){const s=localStorage.getItem('cryptsCreaturesSave');if(!s)return log('No save found.');const d=JSON.parse(s);hero=d.hero;questState=d.questState||questState;activeQuest=d.activeQuest;update();town();log('📂 Save loaded.')}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>window[b.dataset.action]?.());