/* CRYPTS & CREATURES — MEGA WORLD */
const CC={floor:1,wins:0,found:[],ach:[],comp:null};try{Object.assign(CC,JSON.parse(localStorage.getItem('ccMega')||'{}'))}catch(e){}function ccSave(){localStorage.setItem('ccMega',JSON.stringify(CC))}
Object.assign(classes,{monk:{name:'Monk',icon:'🥋',hp:31,atk:9,def:5,ability:'Flurry Strike',desc:'Fast martial artist.'},necromancer:{name:'Necromancer',icon:'💀',hp:27,atk:12,def:3,ability:'Bone Storm',desc:'Commander of the dead.'},artificer:{name:'Artificer',icon:'⚙️',hp:29,atk:9,def:6,ability:'Arcane Cannon',desc:'Magical engineer.'},berserker:{name:'Berserker',icon:'🪓',hp:42,atk:10,def:3,ability:'Rage Cleave',desc:'Unstoppable melee fighter.'}});
const extra=[['Slime','🟢',20,4,1,14,10],['Dire Wolf','🐺',30,8,3,22,16],['Moss Golem','🪨',48,9,8,40,25],['Swamp Witch','🧙',44,11,4,48,32],['Giant Rat','🐀',22,6,2,15,9],['Dark Elf','🧝',38,10,5,35,26],['Mimic','📦',55,12,7,55,45],['Ghost','👻',40,11,3,50,35],['Wraith','🌑',62,13,6,75,55],['Stone Gargoyle','🗿',70,12,10,85,65],['Lich','☠️',85,16,8,120,90],['Demon','😈',95,17,9,145,110],['Frost Giant','🧊',105,16,12,170,125],['Hydra','🐲',130,18,10,210,160],['Shadow Beast','👁️',72,15,7,105,80],['Crystal Drake','💎',88,17,9,140,100],['Forest Ent','🌳',100,14,11,155,120],['Fire Elemental','🔥',76,18,5,130,95],['Ice Elemental','❄️',76,16,8,130,95],['Thunder Roc','🦅',92,19,7,155,115],['Plague Knight','🛡️',78,15,9,135,100],['Sea Serpent','🐍',115,17,9,180,140],['Dread Titan','👹',180,21,13,320,240],['Void Dragon','🐉',240,25,15,500,400]];extra.forEach(x=>{if(!enemies.some(e=>e[0]===x[0]))enemies.push(x)});
function ccHero(){return `<div class="cc-hero-art"><div class="cc-head">${classes[hero.class].icon}</div><div class="cc-body"></div><b>${hero.name}</b></div>`}function ccEnemy(){return `<div class="cc-enemy-art">${enemy.icon}</div>`}
function worldMap(){scene('🗺️ REALM OF EMBERFALL',`<div class="mapGrid"><button onclick="travel('crypt')">☠️<small>Old Crypt</small></button><button onclick="travel('wilds')">🌲<small>Whispering Wilds</small></button><button onclick="travel('swamp')">🐊<small>Murkfen</small></button><button onclick="travel('ruins')">🏛️<small>Sunken Ruins</small></button><button onclick="travel('mountain')">🏔️<small>Frostspire</small></button><button onclick="travel('castle')">🏰<small>Dreadkeep</small></button><button onclick="travel('rift')">🌀<small>Void Rift</small></button><button onclick="town()">🏘️<small>Emberfall</small></button></div>`)}
function travel(x){if(x==='crypt')return crypt();if(x==='wilds')return wilds();if(x==='swamp')return region('🐊 Murkfen',['Swamp Witch','Plague Knight','Sea Serpent']);if(x==='ruins')return region('🏛️ Sunken Ruins',['Mimic','Stone Gargoyle','Crystal Drake']);if(x==='mountain')return region('🏔️ Frostspire',['Frost Giant','Ice Elemental','Thunder Roc']);if(x==='castle')return region('🏰 Dreadkeep',['Lich','Demon','Dread Titan']);if(x==='rift')return region('🌀 Void Rift',['Shadow Beast','Hydra','Void Dragon'])}
function region(title,names){scene(title,'A dangerous region filled with powerful creatures.',names.map(n=>`<button onclick="megaFight('${n.replace(/'/g,"\\'")}')">⚔️ ${n}</button>`).join('')+`<button onclick="worldMap()">🗺️ Map</button><button onclick="town()">🏘️ Town</button>`)}
function megaFight(name){const e=enemies.find(x=>x[0]===name);const i=enemies.indexOf(e);if(i>=0){CC.floor=Math.max(CC.floor,Math.min(25,CC.floor));encounter(i)}}
function dungeon(){scene('☠️ THE DEEP CRYPT',`Floor <b>${CC.floor}</b> — the deeper you go, the stronger the monsters.`,`<button onclick="dungeonFight()">⚔️ Enter Room</button><button onclick="dungeonLoot()">🎁 Search for Treasure</button><button onclick="worldMap()">🗺️ Map</button><button onclick="town()">🏘️ Town</button>`)}
function dungeonFight(){const max=Math.min(enemies.length-1,Math.max(0,CC.floor-1+roll(5)));encounter(max)}function dungeonLoot(){const r=roll(20);if(r>=18){hero.atk+=4;hero.inventory.push('🌟 Legendary Relic');log('🌟 LEGENDARY RELIC! +4 ATK')}else if(r>=10){hero.gold+=50+roll(100);log('💰 Hidden treasure found!')}else{hero.inventory.push(items.greater.name);log('🧪 Greater Potion found!')}CC.floor++;update();ccSave();dungeon()}
function customize(){scene('🎨 CHARACTER CREATOR',`<div class="creator">${ccHero()}<label>Name <input id="heroNameEdit" maxlength="18" value="${hero.name}"></label><p>Current class: ${classes[hero.class].icon} ${classes[hero.class].name}</p><button onclick="saveCustomize()">✨ Save Character</button><button onclick="town()">Back</button></div>`)}function saveCustomize(){hero.name=$('heroNameEdit').value.trim()||hero.name;update();saveGame();customize();log('🎨 Character updated!')}
const companionsData=[['Ember Wolf','🐺',5,2],['Moss Sprite','🌱',2,5],['Clockwork Owl','🦉',4,4],['Skeleton Knight','💀',7,1],['Baby Dragon','🐲',8,3]];function companionsMega(){scene('🐾 COMPANIONS','Choose a permanent companion.',companionsData.map((c,i)=>`<button onclick="hire(${i})">${c[1]} ${c[0]} — +${c[2]} ATK / +${c[3]} DEF</button>`).join('')+`<p>Current: ${CC.comp?CC.comp[0]:'None'}</p><button onclick="town()">Back</button>`)}function hire(i){const c=companionsData[i];if(CC.comp===c)return;CC.comp=c;hero.atk+=c[2];hero.def+=c[3];update();ccSave();log(`🐾 ${c[0]} joined you!`);companionsMega()}
function megaArena(){scene('🏟️ ARENA','Fight ranked champions.',[1,2,3,4].map(r=>`<button onclick="arenaMega(${r})">Rank ${r} — ${r*50}g</button>`).join('')+`<button onclick="town()">Back</button>`)}function arenaMega(r){enemy={name:'Arena Champion '+r,icon:['🥊','⚔️','🛡️','👑'][r-1],maxHp:40+r*30+hero.level*5,hp:40+r*30+hero.level*5,atk:10+r*4+hero.level,def:4+r*2,xp:r*50,gold:r*50};combat('🏟️ The crowd erupts!')}
function forgeMega(){scene('🔨 GRAND FORGE','Use trophies and herbs to permanently upgrade your gear.',`<button onclick="forge('atk')">⚔️ Forge Weapon +3 ATK</button><button onclick="forge('def')">🛡️ Forge Armor +3 DEF</button><button onclick="forge('hp')">❤️ Reinforce Vitality +10 HP</button><button onclick="town()">Back</button>`)}function forge(t){const cost=30;if(hero.gold<cost)return log('Need 30 gold.');hero.gold-=cost;if(t==='atk'){hero.atk+=3;hero.weapon='Masterwork Weapon'}if(t==='def'){hero.def+=3;hero.armor='Masterwork Armor'}if(t==='hp'){hero.maxHp+=10;hero.hp+=10}update();saveGame();log('🔨 Upgrade complete!');forgeMega()}
const oldTownMega=town;town=function(){scene('🏘️ EMBERFALL — CAPITAL OF ADVENTURE','Prepare for your next expedition.',`<button onclick="worldMap()">🗺️ WORLD MAP</button><button onclick="dungeon()">☠️ Deep Crypt</button><button onclick="wilds()">🌲 Wilds</button><button onclick="megaArena()">🏟️ Arena</button><button onclick="companionsMega()">🐾 Companions</button><button onclick="forgeMega()">🔨 Grand Forge</button><button onclick="customize()">🎨 Character Creator</button><button onclick="bestiaryMega()">📖 Bestiary</button><button onclick="worldBoss()">🌋 World Boss</button><button onclick="character()">📊 Character</button><button onclick="inn()">🛏️ Inn</button>`)};
function bestiaryMega(){scene('📖 GRAND BESTIARY',`Discovered <b>${CC.found.length}/${enemies.length}</b><p>${CC.found.join(' • ')||'No creatures discovered yet.'}</p><p>Victories: ${CC.wins}</p><button onclick="town()">Back</button>`)}
const oldWinMega=win;win=function(){oldWinMega();CC.wins++;if(enemy&&!CC.found.includes(enemy.name))CC.found.push(enemy.name);if(hero.inventory&&!hero.inventory.includes('👹 Monster Trophy'))hero.inventory.push('👹 Monster Trophy');if(CC.wins===1)log('🏅 ACHIEVEMENT: First Blood!');if(CC.wins===10)log('🏅 ACHIEVEMENT: Monster Hunter!');if(CC.wins===25)log('🏅 ACHIEVEMENT: Crypt Legend!');ccSave()};
/* Route the old crypt to the new deep dungeon and add map access to the main HUD. */
const oldCryptMega=crypt;crypt=function(){dungeon()};
const oldScene=scene;scene=function(title,text,buttons=''){oldScene(title,`<div class="ccSceneHero">${hero?ccHero():''}</div>${text}`,buttons)};
setTimeout(()=>{if($('classes')&&!$('classes').dataset.mega){$('classes').dataset.mega='1';['monk','necromancer','artificer','berserker'].forEach(id=>{const c=classes[id];$('classes').insertAdjacentHTML('beforeend',`<div class="classCard megaClass" data-class="${id}"><div class="classIcon">${c.icon}</div><h3>${c.name}</h3><p>${c.ability}: ${c.desc}</p><small>HP ${c.hp} • ATK ${c.atk} • DEF ${c.def}</small></div>`);});document.querySelectorAll('.megaClass').forEach(x=>x.onclick=()=>{document.querySelectorAll('.classCard').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');selected=x.dataset.class;$('startBtn').disabled=false})}},100);
ccSave();